// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef pw_h
#define pw_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
extern Fl_Window *PWWind;
#include <FL/Fl_Button.H>
extern Fl_Button *keio;
extern Fl_Button *cancel;
#include <FL/Fl_Input.H>
extern "C" { int password_window(); }
#endif
